"""Add file processing history table

Revision ID: 4260488be38e
Revises: 281eacd4577b
Create Date: 2025-12-26 08:56:41.800348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4260488be38e'
down_revision: Union[str, None] = '281eacd4577b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_processing_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_path', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('ddl_statement', sa.Text(), nullable=False),
    sa.Column('partition_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('num_columns', sa.Integer(), nullable=True),
    sa.Column('num_rows', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_processing_history_created_at'), 'file_processing_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_file_processing_history_id'), 'file_processing_history', ['id'], unique=False)
    op.create_index(op.f('ix_file_processing_history_object_path'), 'file_processing_history', ['object_path'], unique=False)
    op.create_index(op.f('ix_file_processing_history_status'), 'file_processing_history', ['status'], unique=False)
    op.create_index(op.f('ix_file_processing_history_table_name'), 'file_processing_history', ['table_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_processing_history_table_name'), table_name='file_processing_history')
    op.drop_index(op.f('ix_file_processing_history_status'), table_name='file_processing_history')
    op.drop_index(op.f('ix_file_processing_history_object_path'), table_name='file_processing_history')
    op.drop_index(op.f('ix_file_processing_history_id'), table_name='file_processing_history')
    op.drop_index(op.f('ix_file_processing_history_created_at'), table_name='file_processing_history')
    op.drop_table('file_processing_history')
    # ### end Alembic commands ###
