"""remove views column from posts

Revision ID: 4608576a8ca8
Revises: d9faeb76c6c4
Create Date: 2025-12-14 18:17:15.295693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4608576a8ca8'
down_revision: Union[str, None] = 'd9faeb76c6c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
