"""remove views from post table

Revision ID: d9faeb76c6c4
Revises: 281eacd4577b
Create Date: 2025-12-14 16:25:32.035003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9faeb76c6c4'
down_revision: Union[str, None] = '281eacd4577b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'views')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
